version: '3'
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            DATABASE_CONNECTION_TYPE: ${DATABASE_CONNECTION_TYPE}
            DATABASE_CONNECTION_HOST: ${DATABASE_CONNECTION_HOST}
            DATABASE_CONNECTION_PORT: ${DATABASE_CONNECTION_PORT}
            DATABASE_CONNECTION_USERNAME: ${DATABASE_CONNECTION_USERNAME}
            DATABASE_CONNECTION_PASSWORD: ${DATABASE_CONNECTION_PASSWORD}
            DATABASE_CONNECTION_MAINTENANCE: ${DATABASE_CONNECTION_MAINTENANCE}
            POSTGRES_PASSWORD: ${DATABASE_CONNECTION_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        image: redis
        ports:
            - 6379:6379
    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: ghcr.io/joeferner/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8081:8081'
    app:
        build:
            dockerfile: dockerfile
            context: .
            target: development
        ports:
            - '5000:5000'
        restart: always
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        command: npm run start:dev

volumes:
    postgres:
    redis:
    redis-commander:
    app:
