version: '1'
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            # DATABASE_CONNECTION_PROVIDER: ${DATABASE_CONNECTION_PROVIDER}
            DATABASE_CONNECTION_TYPE: ${DATABASE_CONNECTION_TYPE}
            # DATABASE_CONNECTION_HOST: ${DATABASE_CONNECTION_HOST}
            # DATABASE_CONNECTION_PORT: ${DATABASE_CONNECTION_PORT}
            # DATABASE_CONNECTION_USERNAME: ${DATABASE_CONNECTION_USERNAME}
            # DATABASE_CONNECTION_PASSWORD: ${DATABASE_CONNECTION_PASSWORD}
            # DATABASE_CONNECTION_MAINTENANCE: ${DATABASE_CONNECTION_MAINTENANCE}
            DATABASE_CONNECTION_URL: ${DATABASE_CONNECTION_URL}
        volumes:
            - postgres:/var/lib/postgresql/data

    app:
        build:
            dockerfile: dockerfile
            context: .

            target: development
        ports:
            - '5000:5000'

        volumes:
            - .:/usr/src/app

        env_file:
            - .env

        command: npm run start:local

volumes:
    postgres:
    app:
