version: '3'
services:
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        image: redis
        ports:
            - 6379:6379
    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: ghcr.io/joeferner/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8081:8081'
    app:
        build:
            dockerfile: dockerfile
            context: .

            target: development
        ports:
            - '5000:5000'

        volumes:
            - .:/usr/src/app

        env_file:
            - .env

        command: npm run start:local

volumes:
    postgres:
    redis:
    redis-commander:
    app:
