service: bundle-backend

useDotenv: true

plugins:
    - serverless-plugin-optimize
    - serverless-offline

provider:
    name: aws
    runtime: nodejs14.x
    region: eu-north-1
    stage: dev
    timeout: 29
    memorySize: 3008
    environment:
        PORT: ${env:PORT}
        MONGODB_URI: ${env:MONGODB_URI}

        SECRET_KEY: ${env:SECRET_KEY}
        TOKEN_EXPIRATION_TIME: ${env:TOKEN_EXPIRATION_TIME}

        COLLECTION_KEY_ASSEMBLIES: ${env:COLLECTION_KEY_ASSEMBLIES}
        COLLECTION_KEY_APPLICATIONS: ${env:COLLECTION_KEY_APPLICATIONS}
        COLLECTION_KEY_ACCESSORIES: ${env:COLLECTION_KEY_ACCESSORIES}
        COLLECTION_KEY_ORDERS: ${env:COLLECTION_KEY_ORDERS}
        COLLECTION_KEY_PRODUCTS: ${env:COLLECTION_KEY_PRODUCTS}
        COLLECTION_KEY_USERS: ${env:COLLECTION_KEY_USERS}

        ROLE_KEY: ${env:ROLE_KEY}
    apiGateway:
        binaryMediaTypes:
            - '*~1*'
            - '*/*'
            - 'multipart~1form-data'
            - 'multipart/form-data'

functions:
    main:
        handler: dist/serverless.handler
        events:
            - http:
                  cors: true
                  path: '/{any+}'
                  method: any
